server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/jpa_exercise1?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: hyunsik
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug